language: node_js
node_js:
- '8'
before_script:
- npm install
- npm install -g codecov
script:
- npm test
- codecov -f coverage/lcov.info
notifications:
  slack:
    secure: E/O+6gcjD2oTwLnt10w6qEpNQp9AkcuZsy6xsK/Hxw7z47IZwM5BHkUAJhTX0QcJyamZbFaMU9mJ5P4ClLnMPBBj4KV+mznu8yTSySfCub2LKpuGyKIqH3BHqepHbSZiAlMhQkq5OUfW8tOo2p8j6kc5AbvPx6pHCr/nQc0HkjwBQY4SwLb60LGXbPkYsoZhYnXmJmRg/iowu00qakjXH7FInsGist//ZlJp9MiaZH3Cfdo4l3rZn4AJ1naFBD4bNb+Wqqh6zVO4DdOiBVTsq3bZ6vcNZVb2IqlYZvCLODuwhvHiO4wKsQ9QAAhm1TXrraXfs9kR9pMeZeUtnlEeZURu/m7J1Wz2PkBOGGUjCb2xGucppgyg3/1eG3esEL6M6pqVGzuGH1CKjh4aRVZoq47UHDoN+N8Q4ix+TZMqztCFQV47bs56dlmc8hnlluANJsrlJha0p3myYQknv2qjgLjfbZDHoKKybpdAsfaZsDQ3aShw+EtdB38FA0YjsWYQNWh1YmKWBEz1W+jMZ7AlLrkNi20+JHmNngZPW4MQy1Mi0xN905Rlr4RwnzUt5o+pbP78zIlCnZFU5KIIoMDdlKXoZ9hC6gptTajhXkcIjm+FSezy6VUtNpMS0dCSM3RomYWx1MSEpo1XIMzzb6bujBD/XLckejJWAJcTF+PEzz8=
